apiVersion: v1
kind: ConfigMap
metadata:
  name: app-src
data:
  producer.cpp: |
    {{- .Files.Get "apps/producer.cpp" | nindent 4 }}

  consumer.cpp: |
    {{- .Files.Get "apps/consumer.cpp" | nindent 4 }}

  nac-utils.hpp: |
    {{- .Files.Get "apps/nac-utils.hpp" | nindent 4 }}

  kdk-server.cpp: |
    {{- .Files.Get "apps/kdk-server.cpp" | nindent 4 }}
