{{- range .Values.topology }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .node_name }}
  labels:
    app: {{ .node_name }}
spec:
  selector:
    app: {{ .node_name }}
  ports:
    - port: 6363
      targetPort: 6363

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .node_name }}
  labels:
    app: {{ .node_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .node_name }}
  template:
    metadata:
      labels:
        app: {{ .node_name }}
    spec:
      initContainers:
        - name: key-setup
          image: icekarinn/ndn-all:v1.0
          command: ["/bin/bash", "/usr/local/bin/init.sh"]
          volumeMounts:
            - name: ndn-home
              mountPath: /data
            - name: node-secrets
              mountPath: /mnt/secrets
              readOnly: true
            - name: nac-init-script
              mountPath: /usr/local/bin/init.sh
              subPath: init.sh

      containers:
        - name: {{ .node_name }}
          image: icekarinn/ndn-all:v1.0
          tty: true
          env:
            - name: NEIGHBORS
              value: "{{ .neighbors }}"
            - name: HOME
              value: "/data"
          ports:
            - containerPort: 6363
          securityContext:
            privileged: true

          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Pod started. Waiting for activation script..."
              mkdir -p /run/nfd
              mkdir -p /tmp/nlsr
              while true; do sleep 3600; done

          volumeMounts:
            - name: nfd-config-volume
              mountPath: /usr/local/etc/ndn/nfd.conf
              subPath: nfd.conf

            - name: nlsr-config-volume
              mountPath: /etc/nlsr/

            - name: ndn-home
              mountPath: /data

      volumes:
        - name: nfd-config-volume
          configMap:
            name: nfd-config

        - name: nlsr-config-volume
          configMap:
            name: nlsr-config-{{ .node_name }}

        - name: nac-init-script
          configMap:
            name: nac-init-script
            defaultMode: 0755

        - name: node-secrets
          secret:
            secretName: ndn-secret-{{ .node_name }}
            optional: true

        - name: ndn-home
          emptyDir: {}
{{- end }}
