general
{
  network /ndn
  site /jp
  ;values.yamlのndn-node1をnode1に変換
  {{- $shortName := .node_name | trimPrefix "ndn-" }}
  router /%C1.Router/{{ $shortName }}
  lsa-refresh-time 1800
  lsa-interest-lifetime 4
  sync-protocol psync
  sync-interest-lifetime 60000
  state-dir /var/lib/nlsr/
}

neighbors
{
  hello-retries 3
  hello-timeout 1
  hello-interval 60
  adj-lsa-build-interval 10
  face-dataset-fetch-tries 3
  face-dataset-fetch-interval 3600

  ;values.yamlからneighborList=["ndn-node2", "ndn-node4"]を作ってループでneighborを作る
  {{- $neighborList := splitList " " .neighbors -}}
  {{- range $neighborName := $neighborList }}
  neighbor
  {
    {{- $neighborShortName := $neighborName | trimPrefix "ndn-" }}
    name /ndn/jp/%C1.Router/{{ $neighborShortName }}
    face-uri tcp4://{{ $neighborName }}
    link-cost 25
  }
  {{- end }}
}

hyperbolic
{
  state off
  radius   123.456
  angle    1.45,2.36
}

security
{
  validator
  {
    rule
    {
      id "Accept-All"
      for data
      filter
      {
        type name
        regex ^<>*$
      }
      checker
      {
        type customized
        sig-type ecdsa-sha256
        key-locator
        {
          type name
          regex ^<>*$
        }
      }
    }

    trust-anchor
    {
        type any
    }
  }

  prefix-update-validator
  {
    rule
    {
      id "Accept-All-Commands"
      for data
      filter
      {
        type name
        regex ^<>*$
      }
      checker
      {
        type customized
        sig-type ecdsa-sha256
        key-locator
        {
          type name
          regex ^<>*$
        }
      }
    }
    trust-anchor
    {
      type any
      ;file-name "site.cert"
    }
  }

  ; cert-to-publish "root.cert"  ; optional, a file containing the root certificate
                                 ; Only the router that is designated to publish the root cert
                                 ; needs to specify this

  ; cert-to-publish "site.cert"  ; optional, a file containing the site certificate
                                 ; Only the router that is designated to publish the site cert
                                 ; needs to specify this

  ; cert-to-publish "operator.cert" ; optional, a file containing the operator certificate
                                    ; Only the router that is designated to publish the operator
                                    ; cert needs to specify this

  ;cert-to-publish "router.cert"  ; required, a file containing the router certificate.
}
