import os
import yaml

# 設定
WORK_DIR = "/work"
POLICY_FILE = os.path.join(WORK_DIR, "nac-setup", "nac_policy.yaml")
OUT_DIR = os.path.join(WORK_DIR, "nac-setup", "out")

def main():
    print("=== Generating NLSR Advertising Config ===")

    if not os.path.exists(POLICY_FILE):
        print(f"Policy file not found: {POLICY_FILE}")
        return

    with open(POLICY_FILE, 'r') as f:
        policy = yaml.safe_load(f)

    # ノードごとの広報リスト
    node_advertisements = {}
    am_base = policy.get('am_prefix_base', '/ndn/AM')

    # ポリシーから広報Prefixを抽出
    for p in policy.get('policies', []):
        owner_node = p['am_node']
        if owner_node not in node_advertisements:
            node_advertisements[owner_node] = set()

        # 1. KEK配信用のPrefix (/ndn/AM/ndn-node1)
        node_advertisements[owner_node].add(f"{am_base}/{owner_node}")

        # 2. コンテンツPrefix
        # 注: ここで個別のファイルパスではなく、親ディレクトリを集約して登録するロジックを入れると
        # ルーティングテーブルが爆発しません。今回はそのまま追加します。
        for content in p.get('data_contents', []):
            from pathlib import Path
            full_path = content['prefix']
            # 末尾のファイル名 (/index.html) を削る
            parent_prefix = str(Path(full_path).parent)
            node_advertisements[owner_node].add(content['prefix'])

    # ファイル生成
    for node_name, prefixes in node_advertisements.items():
        # 出力先: out/ndn-node1/nlsr-advertising.conf
        node_dir = os.path.join(OUT_DIR, node_name)
        os.makedirs(node_dir, exist_ok=True)

        conf_path = os.path.join(node_dir, "nlsr-advertising.conf")

        print(f"[{node_name}] Writing advertising config...")

        with open(conf_path, 'w') as f:
            f.write("; Generated by NAC Setup\n")
            f.write("advertising\n{\n")
            for prefix in prefixes:
                f.write(f"  prefix {prefix}\n")
            f.write("}\n")

    print("=== Done ===")

if __name__ == "__main__":
    main()
