import yaml
from pathlib import Path

WORK_DIR = Path("/work")
POLICY_FILE = WORK_DIR / "nac-setup" / "nac_policy.yaml"
OUT_DIR = WORK_DIR / "nac-setup" / "out"

def load_policy(path):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Policy file not found: {path}")

    with path.open('r') as f:
        return yaml.safe_load(f)

def get_content_prefix_to_advertise(raw_prefix):
    """
    コンテンツのPrefixを広報用に加工する関数。
    現在はそのまま返すが、将来的に親ディレクトリだけ広報する場合などはここを変更する。
    """
    # 例: 親ディレクトリを集約する場合
    # return str(Path(raw_prefix).parent)
    return raw_prefix

def collect_node_prefixes(policy_data):
    """
    ポリシーデータから、各ノードが広報すべきPrefixのセットを生成する
    Returns: dict { node_name: set(prefixes) }
    """
    node_advertisements = {}

    am_base = policy_data.get('am_prefix_base', '/ndn/AM')
    org_prefix = policy_data.get('org_prefix', '/ndn/test')

    for p in policy_data.get('policies', []):
        owner_node = p['am_node']

        # セットの初期化 (既になければ)
        node_advertisements.setdefault(owner_node, set())

        # 1. Access Manager (KEK配信) 用 Prefix
        node_advertisements[owner_node].add(f"{am_base}/{owner_node}")

        # 2. ノード自身のIdentity Prefix
        identity_prefix = f"{org_prefix}/{owner_node}"
        node_advertisements[owner_node].add(identity_prefix)

        # 3. データコンテンツの Prefix
        for content in p.get('data_contents', []):
            raw_prefix = content['prefix']
            adv_prefix = get_content_prefix_to_advertise(raw_prefix)
            node_advertisements[owner_node].add(adv_prefix)

    return node_advertisements

def write_nlsr_config(node_name, prefixes):
    node_dir = OUT_DIR / node_name
    node_dir.mkdir(exist_ok=True)
    conf_path = node_dir / "nlsr-advertising.conf"

    print(f"[{node_name}] Writing advertising config... ({len(prefixes)} prefixes)")

    with open(conf_path, 'w') as f:
        f.write("; Generated by NAC Setup\n")
        f.write("advertising\n{\n")
        # ソートしておくとdiffが見やすくなる
        for prefix in sorted(list(prefixes)):
            f.write(f"  prefix {prefix}\n")
        f.write("}\n")

def main():
    print("=== Generating NLSR Advertising Config ===")

    try:
        policy_data = load_policy(POLICY_FILE)
        node_prefix_map = collect_node_prefixes(policy_data)
        for node_name, prefixes in node_prefix_map.items():
            write_nlsr_config(node_name, prefixes)
        print(f"=== Done. Files are in '{OUT_DIR}' ===")

    except FileNotFoundError as e:
        print(e)
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()
